Gemstones by Mineral Group:
  - Diamond
  - Beryl Group:
    - Emerald
    - Aquamarine
    - Morganite
    - Heliodor
    - Goshenite
    - Red Beryl (Bixbite)
  - Corundum Group:
    - Ruby
    - Sapphire
    - Pink Sapphire
    - Yellow Sapphire
    - Padparadscha Sapphire
    - Star Sapphire
    - Star Ruby
  - Garnet Group:
    - Pyrope
    - Almandine
    - Spessartine
    - Grossular (Tsavorite, Hessonite)
    - Andradite (Demantoid)
    - Uvarovite
  - Quartz Group:
    - Amethyst
    - Citrine
    - Rose Quartz
    - Smoky Quartz
    - Ametrine
    - Prasiolite
    - Aventurine
    - Tiger's Eye
    - Hawk's Eye
    - Chalcedony
    - Agate
    - Carnelian
    - Jasper
    - Onyx
    - Chrysoprase
  - Feldspar Group:
    - Moonstone
    - Sunstone
    - Labradorite
    - Amazonite
    - Orthoclase
  - Olivine Group:
    - Peridot
  - Spinel Group:
    - Red Spinel
    - Blue Spinel
    - Pink Spinel
  - Tourmaline Group:
    - Rubellite (Pink/Red)
    - Indicolite (Blue)
    - Verdelite (Green)
    - Paraiba Tourmaline
    - Watermelon Tourmaline
    - Black Tourmaline (Schorl)
  - Zircon Group:
    - Blue Zircon
    - Yellow Zircon
    - White Zircon
    - Orange Zircon (Hyacinth)
  - Topaz Group:
    - Imperial Topaz
    - Blue Topaz
    - Pink Topaz
    - Yellow Topaz
    - White Topaz
  - Chrysoberyl Group:
    - Alexandrite
    - Cat's Eye Chrysoberyl
    - Yellow Chrysoberyl
  - Apatite Group:
    - Blue Apatite
    - Green Apatite
    - Yellow Apatite
  - Zoisite Group:
    - Tanzanite
    - Thulite
    - Anyolite (Ruby in Zoisite)
  - Fluorite Group:
    - Purple Fluorite
    - Green Fluorite
    - Blue Fluorite
    - Rainbow Fluorite
  - Jade Group:
    - Jadeite
    - Nephrite


Organic Gemstones:
  - Pearl:
    - Akoya Pearl
    - South Sea Pearl
    - Tahitian Pearl
    - Freshwater Pearl
  - Amber
  - Coral:
    - Red Coral
    - Pink Coral
    - White Coral
    - Black Coral
  - Jet
  - Ivory (Protected)

Other Important Gemstones:
  - Halide Group:
    - Fluorite
  - Carbonate Group:
    - Malachite
    - Azurite
    - Rhodochrosite
    - Calcite
  - Opal:
    - White Opal
    - Black Opal
    - Fire Opal
    - Boulder Opal
    - Crystal Opal
  - Turquoise
  - Lapis Lazuli
  - Sodalite
  - Iolite
  - Kunzite (Spodumene)
  - Hiddenite (Spodumene)

Rare and Collector Gemstones:
  - Kyanite Group:
    - Blue Kyanite
    - Orange Kyanite
  - Andalusite Group:
    - Andalusite
  - Sillimanite Group:
    - Sillimanite
  - Staurolite Group:
    - Staurolite
  - Titanite Group:
    - Sphene (Titanite)
  - Epidote Group:
    - Epidote
  - Axinite Group:
    - Axinite
  - Benitoite
  - Painite
  - Taaffeite
  - Grandidierite
  - Serendibite
  - Musgravite