Gemstones by Mineral Group:
  Carbon:
    - Diamond
  
  Beryl Group:
    - Emerald
    - Aquamarine
    - Morganite
    - Heliodor
    - Goshenite
    - Bixbite
    - Pezzottaite
    - Beryl
  
  Corundum Group:
    - Ruby
    - Sapphire
    - Pink Sapphire
    - Yellow Sapphire
    - Padparadscha Sapphire
  
  Garnet Group:
    - Pyrope
    - Almandine
    - Spessartine
    - Grossular
    - Tsavorite
    - Hessonite
    - Rhodolite
    - Andradite
    - Demantoid
    - Garnet
  
  Quartz Group:
    - Amethyst
    - Citrine
    - Rose Quartz
    - Smoky Quartz
    - Ametrine
    - Prasiolite
    - Quartz
  
  Feldspar Group:
    - Moonstone
    - Sunstone
    - Orthoclase
    - Andesine
  
  Olivine Group:
    - Peridot
  
  Spinel Group:
    - Red Spinel
    - Blue Spinel
    - Pink Spinel
    - Taaffeite
    - Musgravite
    - Vietnamese Purple Spinel
    - Spinel
  
  Tourmaline Group:
    - Rubellite
    - Indicolite
    - Verdelite
    - Paraiba Tourmaline
    - Watermelon Tourmaline
    - Black Tourmaline
    - Pink Tourmaline
    - Tourmaline
  
  Zircon Group:
    - Blue Zircon
    - Yellow Zircon
    - White Zircon
    - Hyacinth
    - Zircon
  
  Topaz Group:
    - Imperial Topaz
    - Blue Topaz
    - Pink Topaz
    - Yellow Topaz
    - White Topaz
    - Topaz
  
  Chrysoberyl Group:
    - Alexandrite
    - Yellow Chrysoberyl
  
  Apatite Group:
    - Blue Apatite
    - Green Apatite
    - Yellow Apatite
    - Apatite
  
  Zoisite Group:
    - Tanzanite
    - Anyolite
  
  Fluorite Group:
    - Purple Fluorite
    - Green Fluorite
    - Blue Fluorite
    - Rainbow Fluorite
  
  Halide Group:
    - Fluorite
  
  Carbonate Group:
    - Rhodochrosite
    - Calcite
    - Bastnasite
  
  Feldspathoid Group:
    - Sodalite
    - Hackmanite
  
  Cyclosilicate Group:
    - Iolite
    - Benitoite
  
  Spodumene Group:
    - Kunzite
    - Hiddenite
    - Spodumene
  
  Pyroxenoid Group:
    - Rhodonite
  
  Pyroxene Group:
    - Diopside
  
  Sorosilicate Group:
    - Danburite
  
  Oxide Group:
    - Diaspore
    - Hibonite
  
  Kyanite Group:
    - Blue Kyanite
    - Orange Kyanite
    - Kyanite
  
  Andalusite Group:
    - Andalusite
  
  Sillimanite Group:
    - Sillimanite
  
  Staurolite Group:
    - Staurolite
  
  Titanite Group:
    - Sphene
  
  Epidote Group:
    - Epidote
  
  Axinite Group:
    - Axinite
  
  Sulfide Group:
    - Sphalerite
  
  Borate Group:
    - Painite
  
  Borosilicate Group:
    - Jeremejevite
    - Grandidierite
    - Serendibite
    - Poudretteite
  
  Humite Group:
    - Clinohumite
    - Chondrodite
  
  Phosphate Group:
    - Vayrynenite
  
  Cancrinite Group:
    - Afghanite
  
  Scapolite Group:
    - Scapolite
  
  Antimonate Group:
    - Kyawthuite