Gemstones by Mineral Group:
  - Diamond
  - Beryl Group:
    - Emerald
    - Aquamarine
    - Morganite
    - Heliodor
    - Goshenite
    - Bixbite
  - Corundum Group:
    - Ruby
    - Sapphire
    - Pink Sapphire
    - Yellow Sapphire
    - Padparadscha Sapphire 
  - Garnet Group:
    - Pyrope
    - Almandine
    - Spessartine
    - Grossular
    - Tsavorite
    - Hessonite
    - Andradite
    - Demantoid 
  - Quartz Group:
    - Amethyst
    - Citrine
    - Rose Quartz
    - Smoky Quartz
    - Ametrine
    - Prasiolite 
  - Feldspar Group:
    - Moonstone
    - Sunstone  
    - Orthoclase
  - Olivine Group:
    - Peridot
  - Spinel Group:
    - Red Spinel
    - Blue Spinel
    - Pink Spinel
    - Taaffeite
    - Musgravite
  - Tourmaline Group:
    - Rubellite 
    - Indicolite  
    - Verdelite  
    - Paraiba Tourmaline
    - Watermelon Tourmaline
    - Black Tourmaline  
  - Zircon Group:
    - Blue Zircon
    - Yellow Zircon
    - White Zircon
    - Hyacinth
  - Topaz Group:
    - Imperial Topaz
    - Blue Topaz
    - Pink Topaz
    - Yellow Topaz
    - White Topaz
  - Chrysoberyl Group:
    - Alexandrite 
    - Yellow Chrysoberyl
  - Apatite Group:
    - Blue Apatite
    - Green Apatite
    - Yellow Apatite
  - Zoisite Group:
    - Tanzanite 
    - Anyolite
  - Fluorite Group:
    - Purple Fluorite
    - Green Fluorite
    - Blue Fluorite
    - Rainbow Fluorite 
 

Other Important Gemstones:
  - Halide Group:
    - Fluorite
  - Carbonate Group: 
    - Rhodochrosite
    - Calcite
    - Bastnasite 
  - Felspadoid Group: 
    - Sodalite
  - Cyclosilicate Group: 
    - Iolite
  - Pyroxene group:
    - Kunzite
    - Hiddenite

Rare and Collector Gemstones:
  - Kyanite Group:
    - Blue Kyanite
    - Orange Kyanite
  - Andalusite Group:
    - Andalusite
  - Sillimanite Group:
    - Sillimanite
  - Staurolite Group:
    - Staurolite
  - Titanite Group:
    - Sphene (Titanite)
  - Epidote Group:
    - Epidote
  - Axinite Group:
    - Axinite
  - Sulfide Group:
    - Sphalerite
  - Cyclosilicate Group:
    - Benitoite
  - Borate Group:
    - Painite
  - borosilicate Group:
    - Jeremejevite
    - Grandidierite
    - Serendibite